# Generated by Django 6.0.1 on 2026-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('source_language', models.CharField(choices=[('en', 'Англійська'), ('uk', 'Українська'), ('pl', 'Польська'), ('de', 'Німецька')], max_length=2)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
