# Generated by Django 6.0.1 on 2026-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='cooldown',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
