# Generated by Django 6.0.1 on 2026-02-09 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_word_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('owner', 'word', 'translation'), name='unique_word_per_user'),
        ),
    ]
